# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (C) 2024 Advanced Micro Devices, Inc.

PACKAGE_NAME=tawk_ipc
PACKAGE_VERSION=0.1.0.dev # Overwritten by `make dist`
AUTOINSTALL=yes

BUILT_MODULE_NAME[0]=tawk_ipc
DEST_MODULE_LOCATION[0]="/extras/tawk_ipc/"

# Workaround for Oracle UEK GCC version. Makefile wraps Kbuild in RHEL SCL.
MAKE[0]="make KSRC=$kernel_source_dir"
MAKE_MATCH[0]="uek"
