// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (C) 2024 Advanced Micro Devices, Inc.

#pragma once


#define IPC_TRANSPORT_HDR_WIDTH 64

#define IPC_TRANSPORT_HDR_TYPE_LBN 0
#define IPC_TRANSPORT_HDR_TYPE_WIDTH 3

#define IPC_TRANSPORT_HDR_TYPE_NOOP 0x0
#define IPC_TRANSPORT_HDR_TYPE_TPMSG 0x1
#define IPC_TRANSPORT_HDR_TYPE_REQ 0x2
#define IPC_TRANSPORT_HDR_TYPE_RSP 0x3
#define IPC_TRANSPORT_HDR_TYPE_TPERR 0x4

#define IPC_TRANSPORT_HDR_OWNER_LBN 7
#define IPC_TRANSPORT_HDR_OWNER_WIDTH 1

/* Only valid for NOOP */
#define IPC_TRANSPORT_HDR_NOOP_RSVD0_LBN 8
#define IPC_TRANSPORT_HDR_NOOP_RSVD0_WIDTH 56

/* Only valid for TPMSG */
#define IPC_TRANSPORT_HDR_TPMSG_MSGCODE_LBN 8
#define IPC_TRANSPORT_HDR_TPMSG_MSGCODE_WIDTH 8

#define IPC_TRANSPORT_HDR_TPMSG_CFG_VER 0x1
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS 0x2
#define IPC_TRANSPORT_HDR_TPMSG_READY 0x4

/* Only valid for REQ, RSP and TPERR */
#define IPC_TRANSPORT_HDR_TAG_LBN 8
#define IPC_TRANSPORT_HDR_TAG_WIDTH 8

/* Only valid for REQ and RSP; required to
 * be zero for TPMSG and TPERR */
#define IPC_TRANSPORT_HDR_PLD_LEN_LBN 16
#define IPC_TRANSPORT_HDR_PLD_LEN_WIDTH 16

/* Only valid for TPMSG/CFG_VER */
#define IPC_TRANSPORT_HDR_TPMSG_CFG_VER_MIN_LBN 32
#define IPC_TRANSPORT_HDR_TPMSG_CFG_VER_MIN_WIDTH 16
#define IPC_TRANSPORT_HDR_TPMSG_CFG_VER_MAX_LBN 32
#define IPC_TRANSPORT_HDR_TPMSG_CFG_VER_MAX_WIDTH 16

/* Only valid for TPMSG/CFG_CAPS */
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS_INI_MAX_LBN 32
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS_INI_MAX_WIDTH 16
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS_INI_MAX_INFINITE 0xffff
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS_TGT_MAX_LBN 48
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS_TGT_MAX_WIDTH 16
#define IPC_TRANSPORT_HDR_TPMSG_CFG_CAPS_TGT_MAX_INFINITE 0xffff

/* Only valid for TPMSG/READY */
#define IPC_TRANSPORT_HDR_TPMSG_READY_RSVD0_LBN 32
#define IPC_TRANSPORT_HDR_TPMSG_READY_RSVD0_WIDTH 32

/* Only valid for REQ */
#define IPC_TRANSPORT_HDR_REQ_ENDPOINT_LBN 32
#define IPC_TRANSPORT_HDR_REQ_ENDPOINT_WIDTH 32

/* Only valid for RSP */
#define IPC_TRANSPORT_HDR_RSP_ERRNO_LBN 32
#define IPC_TRANSPORT_HDR_RSP_ERRNO_WIDTH 32

/* Only valid for TPERR */
#define IPC_TRANSPORT_HDR_TPERR_ERRCODE_LBN 32
#define IPC_TRANSPORT_HDR_TPERR_ERRCODE_WIDTH 32

/* Request not handled because the link went down.
 * Never used on the wire, but conveniant to have. */
#define IPC_TRANSPORT_HDR_TPERR_NOLINK 0x1

/* Request not handled because no endpoint handler is
 * registered */
#define IPC_TRANSPORT_HDR_TPERR_NOEP 0x2
