/* SPDX-License-Identifier: GPL-2.0 */
/* Static autocompat.h for Linux kernel 6.12 (SONiC aarch64/mnic build).
 * Normally generated by kcompat.sh for host builds; for the mnic/aarch64
 * cross-build path this file is committed directly since the generation
 * script is not run.  All features below are verified present in kernel 6.12.
 */

#ifndef _IONIC_AUTOCOMPAT_H_
#define _IONIC_AUTOCOMPAT_H_

/* devlink — kernel 6.12 uses devlink_alloc_ns/devlink_alloc with dev param */
#define IONIC_HAVE_DEVLINK_ALLOC_DEV
/* devlink_register() returns void since 5.15 */
#define IONIC_HAVE_VOID_DEVLINK_REGISTER
/* devlink_info_driver_name_put removed — use no-op wrapper */
/* IONIC_HAVE_DEVLINK_DRIVER_NAME_PUT not set */
/* SET_NETDEV_DEVLINK_PORT present since 6.1 */
#define IONIC_HAVE_SET_NETDEV_DEVLINK_PORT
/* devlink_params_publish removed in 5.18 — do not define */
/* IONIC_HAVE_DEVLINK_PARAMS_PUBLISH not set */
/* devlink_param get/set requires extack param in kernel 6.12 */
#define IONIC_HAVE_DEVLINK_EXT_ACK_PARAM
/* DEVLINK_INFO_VERSION_GENERIC_FW_PSID (rdma id) not present — do not define */
/* IONIC_HAVE_DEVLINK_GENERIC_RDMA_ID not set */

/* skb / networking — all present in 6.12 */
#define IONIC_HAVE_TCP_ALL_HEADERS
#define IONIC_HAVE_INNER_TCP_ALL_HEADERS
#define IONIC_HAVE_SKB_FRAG_FILL_PD

/* ethtool — kernel 6.12 has ethtool_rxfh_param struct */
#define IONIC_HAVE_RXFH_PARAM
/* kernel_ethtool_ts_info present since 6.7 */
#define IONIC_HAVE_KERNEL_ETHTOOL_TS_INFO
/* get_module_eeprom_by_page present since 5.15 */
#define IONIC_HAVE_MODULE_EEPROM_BY_PAGE
/* set_ringparam takes kernel_ethtool_ringparam + extack since 5.17 */
#define IONIC_HAVE_ETHTOOL_SET_RINGPARAM_EXTACK
/* ethtool coalesce cqe (use_cqe_mode_tx/rx) present since 5.18 */
#define IONIC_HAVE_ETHTOOL_COALESCE_CQE

/* misc kernel API */
#define IONIC_HAVE_TIMER_DELETE
/* timer_container_of removed in kernel 5.15+ — use from_timer instead */
/* IONIC_HAVE_TIMER_CONTAINER_OF not set */
#define IONIC_HAVE_SMP_STORE_MB
#define IONIC_HAVE_DMA_MAPPING_ERROR
#define IONIC_HAVE_NDO_ETH_IOCTL
#define IONIC_HAVE_NDO_VF_VLAN_PROTO

/* ptp: cc_read callback takes const struct cyclecounter * in 6.12 */
#define IONIC_HAVE_PHC_CC_READ_CONST

/* net_dim takes dim_sample by value (not pointer) in 6.12 — do not define */
/* IONIC_HAVE_NET_DIM_SAMPLE_PTR not set */

#endif /* _IONIC_AUTOCOMPAT_H_ */
