// SPDX-License-Identifier: MIT or GPL-2.0-only
// SPDX-FileCopyrightText: Copyright (C) 2024 Advanced Micro Devices, Inc.

#pragma once

#define TAWK_IPC_PCIE_HDR_MAGIC_REG              0x00
#define TAWK_IPC_PCIE_HDR_MAGIC {'T', 'A', 'W', 'K'} /* in ASCII */

#define TAWK_IPC_PCIE_HDR_VER_REG                0x04

#define TAWK_IPC_PCIE_HDR_CAP_REG                0x08
#define TAWK_IPC_PCIE_HDR_CAP_PEER_ID_LBN   0
#define TAWK_IPC_PCIE_HDR_CAP_PEER_ID_WIDTH 1
#define TAWK_IPC_PCIE_HDR_CAP_INTERRUPTS_LBN   1
#define TAWK_IPC_PCIE_HDR_CAP_INTERRUPTS_WIDTH 1
#define TAWK_IPC_PCIE_HDR_CAP_INTR_ASSN_LBN    2
#define TAWK_IPC_PCIE_HDR_CAP_INTR_ASSN_WIDTH  1
#define TAWK_IPC_PCIE_HDR_CAP_INTR_REGS_LBN    3
#define TAWK_IPC_PCIE_HDR_CAP_INTR_REGS_WIDTH  1

#define TAWK_IPC_PCIE_HDR_STA_REG                0x0c

#define TAWK_IPC_PCIE_HDR_CTL_REG                0x10
#define TAWK_IPC_PCIE_HDR_CTL_INTERRUPT_EN_LBN 0
#define TAWK_IPC_PCIE_HDR_CTL_INTERRUPT_EN_WIDTH 1

#define TAWK_IPC_PCIE_HDR_INT_VEC_RST_REG        0x20
#define TAWK_IPC_PCIE_HDR_INT_VEC_MBOX_REG       0x24

#define TAWK_IPC_PCIE_HDR_INTR_REGS_BIR_OFFS_REG 0x2c
#define TAWK_IPC_PCIE_HDR_INTR_REGS_BIR_LBN   0
#define TAWK_IPC_PCIE_HDR_INTR_REGS_BIR_WIDTH 3
#define TAWK_IPC_PCIE_HDR_INTR_REGS_OFFS_32_3_LBN    3
#define TAWK_IPC_PCIE_HDR_INTR_REGS_OFFS_32_3_WIDTH 29



#define TAWK_IPC_PCIE_HDR_DBELL_RST_OFFS_REG     0x30
#define TAWK_IPC_PCIE_HDR_DBELL_RST_VAL_REG      0x34
#define TAWK_IPC_PCIE_HDR_DBELL_MBOX_OFFS_REG    0x38
#define TAWK_IPC_PCIE_HDR_DBELL_MBOX_VAL_REG     0x3c

#define TAWK_IPC_PCIE_HDR_RST_SIGS_IN_OFFS_REG   0x50
#define TAWK_IPC_PCIE_HDR_RST_SIGS_OUT_OFFS_REG  0x54

#define TAWK_IPC_PCIE_HDR_MBOX_COUNT_REG         0x60
#define TAWK_IPC_PCIE_HDR_MBOX_CTL_OFFS_REG      0x68
#define TAWK_IPC_PCIE_HDR_MBOX_CTL_STRIDE_REG    0x6c
#define TAWK_IPC_PCIE_HDR_MBOX_BUF_OFFS_REG      0x70
#define TAWK_IPC_PCIE_HDR_MBOX_BUF_STRIDE_REG    0x74
#define TAWK_IPC_PCIE_HDR_MBOX_BUF_SIZE_REG      0x78
